### ISSUE TITLE
Can you help with this sed?

### ISSUE THREAD

**Issue by AcarBurak** [bgr/imdb-cli#5]
Thanks a lot for this brilliant utility.

I want to get this in one line:

TITLE - DIRECTOR - ACTORS - YEAR

But with

`imdbtool -t "adam's rib" | sed -n '/^title/{n;p;}; /^director/{n;p;}; /^actors/{n;p;}; /^year/{n;p;}' | sed ':a;N;$!ba;s/\n/ - /g'`

I get it in inconsistent order like so:

DIRECTOR - ACTORS - TITLE - YEAR

Because of imdb-cli's output variatıon, that is, its output order is not consistent on every fetch. How to overcome this if possible?

Well, not elegant, but this works:

`( imdbtool -t "casablanca" | sed -n '/^title/{n;p;}' ; imdbtool -t "casablanca" | sed -n '/^director/{n;p;}' ; imdbtool -t "casablanca" | sed -n '/^actors/{n;p;}' ; imdbtool -t "casablanca" | sed -n '/^year/{n;p;}' ) | cat | sed ':a;N;$!ba;s/\n/ - /g'`

**Comment by bgr** [comment]
I was going to suggest that  `sed ':a;N;$!ba;s/\n/ - /g'` thing, but I see you found it already ([stackoverflow](http://stackoverflow.com/a/1252191) ftw).

I'll take a look into what causes the inconsistency later in the evening.

**Comment by AcarBurak** [comment]
Thank you.

**Comment by bgr** [comment]
Check out the branch "predictability" and see if it helps. The sections will always be sorted in alphabetical order (I guess "lexicographical" would be more correct). 

Note that this branch includes a lot of other changes, most important of all is that it now uses omdbapi since the old api is now defunct.

**Comment by AcarBurak** [comment]
Script outputs some errors:

```
imdbtool.py", line 38
    print result
               ^
SyntaxError: Missing parentheses in call to 'print'
```

```
imdbtool.py", line 45
    print k.lower() + ":"
          ^
SyntaxError: invalid syntax
```

```
imdbtool.py", line 46
    print data[k].encode('utf-8')
             ^
SyntaxError: invalid syntax
```

```
imdbtool.py", line 47
    print "\n"
             ^
SyntaxError: Missing parentheses in call to 'print'
```

I've added paranthesis to all these like so:

```
apicall = urllib.urlopen('http://www.imdbapi.com/?%s' % urllib.urlencode(params))
result = apicall.read()
apicall.close()

# print raw output and exit, if raw output was requested
if args.r:
  print (result)
  sys.exit()

# print requested info

data = json.loads(result)
for k in data:
  print (k.lower) + ":"
  print (data[k]).encode('utf-8')
  print ("\n")
```

But then:

```
imdbtool.py -t casablanca
Traceback (most recent call last):
  File "/home/burak/bin/imdb-cli/imdbtool.py", line 32, in <module>
    apicall = urllib.urlopen('http://www.imdbapi.com/?%s' % urllib.urlencode(params))
AttributeError: module 'urllib' has no attribute 'urlopen'
```

**Comment by bgr** [comment]
Something's messed up, there is no "imdbtool.py" on that branch anymore, it's "omdbtool.py" now.

**Comment by AcarBurak** [comment]
Very sorry, I've cloned from the predictibilty page and the master has been fetched. Now I've downloaded the archive which is the correct one.

**Comment by AcarBurak** [comment]
Yes, it works consistently now, yet doesn't solve my issue which is argued mistakenly because of my noobness. That is, even if the fetching is consistent the sed output naturally cannot be in an arbitrary order  like mine. So sorry for the noise. And I can use my above workaround.

The new markdown and html output features are very fine by the way.

Thank you.
