### ISSUE TITLE
Release for packaging

### ISSUE THREAD

**Issue by Booloki** [bgr/imdb-cli#7]
Hi,

I would like to rebase the imdb-cli AUR package (https://aur.archlinux.org/packages/imdb-cli) upstream.
But there's no imdb-cli release (git tag) for now. Can you provide one ?
If possible with a version number > 2.2 . If not, already installed imdb-cli packages will not be updated.

Thanks.

**Comment by bgr** [comment]
Made a release, check it out.

**Comment by Booloki** [comment]
Package is updated.
Thanks a lot!
